[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
build_info = true
extra_output = ["storageLayout"]
optimizer = true
optimizer_runs = 200
solc = "0.8.21"
# See more config options https://github.com/foundry-rs/foundry/tree/master/config
